name: App CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Run linter and tests
        run: |
          yarn run lint
          docker-compose up -d mongo
          yarn test -- --verbose --coverage
        continue-on-error: true
      - run: docker-compose build
      - run: docker-compose logs
        if: always()
      - run: docker-compose down --volumes
        if: always()
